image:
  file: .gitpod.Dockerfile

# Workspace startup
tasks:
  - init: cd todo-api && nginx
    command: npm run start:frontail
  - openMode: tab-after
    command: clear && gp await-port 3000 && bin/start

# Ports to expose on workspace
ports:
  - name: api
    port: 3000
    onOpen: ignore
  - name: frontail
    port: 9001
    onOpen: ignore
  - name: tutorial
    port: 8002
    onOpen: open-preview
