image:
  file: .gitpod.Dockerfile

# Workspace startup
tasks:
  - init: cd todo-api && npm install && nginx
    command: npm start
  - openMode: tab-after
    command: clear && gp await-port 3000 && cat .tutorial/banner.txt

# Ports to expose on workspace
ports:
  - port: 3000
    onOpen: ignore
